const ADD_TODO = 'ADD_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const EDIT_TODO = 'EDIT_TODO';
const CHANGE_SCREEN = 'CHANGE_SCREEN';
const SHOW_LOADER = 'SHOW_LOADER';
const HIDE_LOADER = 'HIDE_LOADER';
const SHOW_ERROR = 'SHOW_ERROR';
const HIDE_ERROR = 'HIDE_ERROR';
const FETCH_TODOS = 'FETCH_TODOS';

export {
  ADD_TODO,
  REMOVE_TODO,
  EDIT_TODO,
  CHANGE_SCREEN,
  SHOW_LOADER,
  HIDE_LOADER,
  SHOW_ERROR,
  HIDE_ERROR,
  FETCH_TODOS,
};
